import Head from 'next/head'
import Link from 'next/link'

import React, { useState } from 'react'

import { NavBar } from '../../components/nav-bar'
import { IconButton } from '../../components/icon-button'
import { Card } from '../../components/card'
import { Input } from '../../components/input'

export default function Design() {
  const [skillValue, setSkillValue] = useState('')
  const [locationValue, setLocationValue] = useState('')

  const skillHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setSkillValue(event.target.value)
  }
  const locationHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setLocationValue(event.target.value)
  }

  return (
    <div>
      <Head>
        <title>GoodHive | Design System</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main className="mx-5">
        <h1 className="text-3xl font-bold font-montserrat">
          Looking for Talent
        </h1>

        <section className="mt-5 body-font font-montserrat">
          <div className="grid min-w-full grid-cols-1 grid-flow-row sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-2 2xl:grid-cols-2 3xl:grid-cols-2 4xl:grid-cols-3 gap-3">
            <div className="grid justify-items-left mx-1">
              <Input
                labelText="Skill"
                placeholder="Try with: Solidity Developer"
                type="text"
                required={true}
                disabled={false}
                value={skillValue}
                onChange={skillHandleChange}
              ></Input>
              <Input
                labelText="Location"
                placeholder="Try with: Paris or London"
                type="text"
                required={true}
                disabled={false}
                value={locationValue}
                onChange={locationHandleChange}
              ></Input>
            </div>
          </div>
        </section>

        <section className="mt-5 body-font font-montserrat">
          <span className="mr-5">
            <IconButton
              text="Post a Job"
              type="secondary"
              size="large"
              image="M184 48H328c4.4 0 8 3.6 8 8V96H176V56c0-4.4 3.6-8 8-8zm-56 8V96H64C28.7 96 0 124.7 0 160v96H192 320 512V160c0-35.3-28.7-64-64-64H384V56c0-30.9-25.1-56-56-56H184c-30.9 0-56 25.1-56 56zM512 288H320v32c0 17.7-14.3 32-32 32H224c-17.7 0-32-14.3-32-32V288H0V416c0 35.3 28.7 64 64 64H448c35.3 0 64-28.7 64-64V288z"
            ></IconButton>
          </span>
          <span>
            <IconButton
              text="Search Talent"
              type="primary"
              size="large"
              image="M416 208c0 45.9-14.9 88.3-40 122.7L502.6 457.4c12.5 12.5 12.5 32.8 0 45.3s-32.8 12.5-45.3 0L330.7 376c-34.4 25.2-76.8 40-122.7 40C93.1 416 0 322.9 0 208S93.1 0 208 0S416 93.1 416 208zM208 352c79.5 0 144-64.5 144-144s-64.5-144-144-144S64 128.5 64 208s64.5 144 144 144z"
            ></IconButton>
          </span>
        </section>

        <section className="mt-5 body-font font-montserrat">
          <h2 className="text-2xl font-bold">Search Results</h2>
          <h3 className="text-xl mt-2">Talent Listings</h3>
          <div className="grid min-w-fit grid-cols-1 grid-flow-row sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-2 2xl:grid-cols-2 3xl:grid-cols-2 4xl:grid-cols-3 gap-3">
            <Card
              type="talent"
              title="Talent 1 Position"
              postedBy="Talent Name"
              postedOn="Active 4 days ago"
              image="/img/talent_avatar.png"
              countryFlag="/img/country_flag.png"
              city="Paris"
              rate="75"
              currency="EUR"
              description="Talent profile description will come here when posted Amet, consecq consec consectetur adipiscing elit, sed do eiusmod."
              skills={['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4']}
              buttonText="Connect"
              escrowFee=""
            />
            <Card
              type="talent"
              title="Talent 2 Position"
              postedBy="Talent Name"
              postedOn="Active 3 days ago"
              image="/img/talent_avatar.png"
              countryFlag="/img/country_flag.png"
              city="Hyderabad"
              rate="50"
              currency="USD"
              description="Talent profile description will come here when posted Amet, consecq consec consectetur adipiscing elit, sed do eiusmod."
              skills={['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4']}
              buttonText="Connect"
              escrowFee=""
            />
            <Card
              type="talent"
              title="Talent 3 Position"
              postedBy="Talent Name"
              postedOn="Active 2 days ago"
              image="/img/talent_avatar.png"
              countryFlag="/img/country_flag.png"
              city="San Francisco"
              rate="120"
              currency="USD"
              description="Talent profile description will come here when posted Amet, consecq consec consectetur adipiscing elit, sed do eiusmod."
              skills={['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4']}
              buttonText="Connect"
              escrowFee=""
            />
          </div>
        </section>
      </main>

      <footer className="mx-5 my-3 font-light text-sm">
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by GoodHive
        </Link>
      </footer>
    </div>
  )
}
