import Head from 'next/head'
import Link from 'next/link'

import React, { useState } from 'react'

import { NavBar } from '../../components/nav-bar'
import { Button } from '../../components/button'
import { Card } from '../../components/card'
import { Input } from '../../components/input'

export default function Design() {
  const [textValue, setTextValue] = useState('')
  const [numberValue, setNumberValue] = useState('')
  const [emailValue, setEmailValue] = useState('')
  const [passwordValue, setPasswordValue] = useState('')
  const [urlValue, setURLValue] = useState('')

  const textHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setTextValue(event.target.value)
  }
  const numberHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setNumberValue(event.target.value)
  }
  const emailHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setEmailValue(event.target.value)
  }
  const passwordHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setPasswordValue(event.target.value)
  }
  const urlHandleChange = (event: React.ChangeEvent<HTMLInputElement>) => {
    setURLValue(event.target.value)
  }

  return (
    <div>
      <Head>
        <title>GoodHive | Design System</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css?family=Montserrat"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />

      <main className="mx-5">
        <h1 className="text-3xl font-bold font-montserrat">
          Looking for Talent
        </h1>

        <section className="mt-5 body-font font-montserrat">
          <div className="grid min-w-full grid-cols-1 grid-flow-row sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-2 2xl:grid-cols-2 3xl:grid-cols-2 4xl:grid-cols-3 gap-3">
            <div className="grid justify-items-left mx-1">
              <Input
                labelText="Skill"
                placeholder="Try with: Solidity Developer"
                type="text"
                required={true}
                disabled={false}
                value={textValue}
                onChange={textHandleChange}
              ></Input>
              <Input
                labelText="Location"
                placeholder="Try with: Paris or London"
                type="text"
                required={true}
                disabled={false}
                value={textValue}
                onChange={textHandleChange}
              ></Input>
            </div>
          </div>
        </section>

        <section className="mt-5 body-font font-montserrat">
          <span className="mr-5">
            <Button text="Post a Job" type="secondary" size="large"></Button>
          </span>
          <span>
            <Button text="Search Talent" type="primary" size="large"></Button>
          </span>
        </section>

        <section className="mt-5 body-font font-montserrat">
          <h2 className="text-2xl font-bold">Search Results</h2>
          <h3 className="text-xl mt-2">Talent Listings</h3>
          <div className="grid min-w-fit grid-cols-1 grid-flow-row sm:grid-cols-1 md:grid-cols-1 lg:grid-cols-1 xl:grid-cols-2 2xl:grid-cols-2 3xl:grid-cols-2 4xl:grid-cols-3 gap-3">
            <Card
              title="Talent 1 Position"
              postedBy="Talent Name"
              postedOn="Active 4 days ago"
              image="/img/talent_avatar.png"
              countryFlag="/img/country_flag.png"
              city="Paris"
              rate="$75 USD/hour"
              description="Talent profile description will come here when posted Amet, consecq consec consectetur adipiscing elit, sed do eiusmod."
              skills={['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4']}
              buttonText="Connect"
            />
            <Card
              title="Talent 2 Position"
              postedBy="Talent Name"
              postedOn="Active 3 days ago"
              image="/img/talent_avatar.png"
              countryFlag="/img/country_flag.png"
              city="Hyderabad"
              rate="$50 USD/hour"
              description="Talent profile description will come here when posted Amet, consecq consec consectetur adipiscing elit, sed do eiusmod."
              skills={['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4']}
              buttonText="Connect"
            />
            <Card
              title="Talent 3 Position"
              postedBy="Talent Name"
              postedOn="Active 2 days ago"
              image="/img/talent_avatar.png"
              countryFlag="/img/country_flag.png"
              city="San Francisco"
              rate="$120 USD/hour"
              description="Talent profile description will come here when posted Amet, consecq consec consectetur adipiscing elit, sed do eiusmod."
              skills={['Skill 1', 'Skill 2', 'Skill 3', 'Skill 4']}
              buttonText="Connect"
            />
          </div>
        </section>

        <section className="mt-5 body-font font-montserrat">
          <h2 className="text-2xl font-bold">Metamask</h2>
        </section>
      </main>

      <footer className="mx-16">
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by GoodHive
        </Link>
      </footer>
    </div>
  )
}
