import Head from "next/head";
import Link from "next/link";

import { NavBar } from "../components/nav-bar";

export default function Home() {

  return (
    <div>
      <Head>
        <title>GoodHive</title>
        <meta name="description" content="Generated by create next app" />
        <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <main className="mx-5">
        <h1 className="mt-5 text-2xl">Home Page</h1>
        <p className="my-10 text-lg">Get started by clicking on the Design System</p>
      </main>

      <footer className="mx-5 text-sm">
        <Link
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '} GoodHive
        </Link>
      </footer>
    </div>
  )
}
